services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=S@meComplexPassw0rd
    ports:
      - "1434:1433"
    volumes:
      - sqlserver:/var/opt/mssql

volumes:
  sqlserver:
