services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=S@meComplexPassw0rd
    ports:
      - "1434:1433"
    volumes:
      - sqlserver:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-api
    ports:
      - 7000:8080
    depends_on:
      - sqlserver
    environment:
        - ASPNETCORE_ENVIRONMENT=Staging

  blog-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.0.0
    container_name: blog-dashboard
    ports:
      - 18888:18888
      - 4317:18889
    depends_on:
      - sqlserver
      - api
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true

volumes:
  sqlserver:
